apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  MONGO_URI: { { .Values.secrets.mongoUri | quote } }
  JWT_SECRET: { { .Values.secrets.jwtSecret | quote } }
  CLOUDINARY_CLOUD_NAME: { { .Values.secrets.cloudinary.cloudName | quote } }
  CLOUDINARY_API_KEY: { { .Values.secrets.cloudinary.apiKey | quote } }
  CLOUDINARY_API_SECRET: { { .Values.secrets.cloudinary.apiSecret | quote } }
